"""
Generated by Copilot

Pygame 벽돌깨기 게임의 주요 객체에 대한 간단한 테스트 코드.
PEP 8, PEP 257, PEP 484 스타일 가이드 준수.
"""
import sys
import os
import pygame
import unittest

# src 모듈 임포트 경로 추가
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))
from brick import BrickSprite
from ball import BallSprite

class TestBrickBall(unittest.TestCase):
    def setUp(self) -> None:
        pygame.init()
        self.screen_rect = pygame.Rect(0, 0, 600, 400)
        self.brick = BrickSprite(x=100, y=350)
        self.ball = BallSprite(x=120, y=340)

    def tearDown(self) -> None:
        pygame.quit()

    def test_brick_move_left(self):
        keys = [0] * 512
        keys[pygame.K_LEFT] = 1
        self.brick.update(keys)
        self.assertLess(self.brick.rect.x, 100)

    def test_ball_bounce_on_brick(self):
        # 공이 벽돌과 충돌하면 y방향 속도가 반전되는지 확인
        self.ball.rect.bottom = self.brick.rect.top
        self.ball.velocity = [0, 5]
        self.ball.update(self.brick, self.screen_rect)
        self.assertLess(self.ball.velocity[1], 0)

    def test_ball_bounce_on_wall(self):
        # 공이 왼쪽 벽에 닿으면 x방향 속도가 반전되는지 확인
        self.ball.rect.left = 0
        self.ball.velocity = [-5, 0]
        self.ball.update(self.brick, self.screen_rect)
        self.assertGreater(self.ball.velocity[0], 0)

# Brick, Ball 클래스 정의 또는 import 필요

if __name__ == "__main__":
    unittest.main()
